### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [el-NASA/POA#12]
By including the "POA/Libraries/Arduino-MS5611" library, you have included wrong use of the Wire library in the file "MS5611.cpp"

See my issue for the MS5611.cpp: https://github.com/jarzebski/Arduino-MS5611/issues/2

The file "MPU6050.cpp" has the same issues: https://github.com/jarzebski/Arduino-MPU6050/issues/4

The file "flyMPU6050.ino" has this issue: https://github.com/VRomanov89/EEEnthusiast/issues/1

**Comment by el-NASA** [comment]
wow thanks man, i'll be working on that, thanks for posting the issue.

**Comment by el-NASA** [comment]
hey man, i fixed the issue according to your instrucions and the info in your profile, thanks again for posting it.

**Comment by Koepel** [comment]
I did a search for "requestFrom" and it is used in six files. I have checked those six files, and I think it is all right.

Did you notice that the `fastRegister8` and `readRegister8` functions are exactly the same, once the issues has been solved ? There has never been a slow and fast way to do I2C.

Some leftovers are at: "POA/FlightComps(in development)/FlyI2C/flyMS5611/flyMS5611.ino"
Requesting 24 bytes and using only 1, and a while to wait. That is weird.

**Comment by el-NASA** [comment]
Hello man, i fixed the issue, the fastRegister8 only was used once, but readRegister8 is used a lot more, anyway it was fixed, and for the flyMS5611.ino i fixed as well, but it is not working very good, it can only read a registry but in the max value(that is super weird and obviously something is wrong).

 thanks again for posting the issue, i will keep the issue open if you find another problem.

**Comment by Koepel** [comment]
The setup function `MS5611SetUp()` is also called from the loop(). There are a few other MS5611 libraries on Github. I suggest to compare your code with those. You may start with this one: https://github.com/RobTillaart/Arduino/tree/master/libraries/MS5611
